### ISSUE TITLE
don`t work on attribute selectors

### ISSUE THREAD

**Issue by Scrum** [thompsongl/postcss-class-prefix#10]
don`t work on attribute selectors

``` css
[class*="myclassname"]
```

**Comment by peterver** [comment]
+1

**Comment by Scrum** [comment]
@peterver this project long not supported :( I created new project [postcss-attribute-selector-prefix](https://github.com/GitScrum/postcss-attribute-selector-prefix), but me don`t have time so far. Watch my project if interested.

**Comment by Scrum** [comment]
@peterver Hi, i`m create plugin [postcss-attribute-selector-prefix](https://github.com/GitScrum/postcss-attribute-selector-prefix). Good use.
