### ISSUE TITLE
Support for Webpack PostCSS Loader

### ISSUE THREAD

**Issue by TheLarkInn** [thompsongl/postcss-class-prefix#11]
Can we have some support for this to work with webpack and the PostCSS Loader. So that your compiled bundled CSS can then be prefixed. (Such as like a post-module-loader).

**Comment by thompsongl** [comment]
This plugin already works with the webpack postcss-loader; both the plugin and plugin pack methods described [here](https://github.com/postcss/postcss-loader#usage) have worked.
As far as wanting it to act on the compiled CSS, the output should be the same if you plug into the normal loader chain (taking care to make the order sensible regarding all your other plugins). Additionally, webpack indicates reserving postLoaders for test coverage plugins, so I'm not sure how a CSS task would be handled there.

**Comment by antonsivogrivov** [comment]
Ok, could you give some example?

**Comment by antonsivogrivov** [comment]
Ok, I found https://gist.github.com/ronen-e/17db4566bb0d14cf331b53be92578ae2

**Comment by thompsongl** [comment]
Officially (finally) marked this repo as no longer in active maintenance and cleaning up issues.
Closing due to that, time, and the fact that Sean (Hi, @TheLarkInn 👋) probably no longer uses this.
