### ISSUE TITLE
Allow using with comments

### ISSUE THREAD

**Issue by Grawl** [thompsongl/postcss-class-prefix#12]
I want to use it only for parts of my CSS, such as:

``` css
/* postcss-class-prefix: foo- */
.a {}
.b {}
/* postcss-class-prefix: end */
```

to get it prefixed:

``` css
/* postcss-class-prefix: foo- */
.foo-a {}
.foo-b {}
/* postcss-class-prefix: end */
```

Or so.

**Comment by thompsongl** [comment]
Sorry for my awful communication, here. I don't plan on adding new functionality, but if you're still looking, https://github.com/marceloucker/postcss-prefixer may be helpful.
