### ISSUE TITLE
First usage example not working

### ISSUE THREAD

**Issue by steveharrison** [thompsongl/postcss-class-prefix#15]
Hey I tried the first code snippet in your Usage section as is, but the resulting `css` parameter in the output was `undefined`. Looks like the PostCSS API might have changed or something? I modified it based on some recent PostCSS examples to get this working snippet:
```
var fs        = require('fs');
var postcss   = require('postcss');
var classPrfx = require('postcss-class-prefix');

var css = fs.readFileSync('my-file.css', 'utf8').toString();
var out = postcss([classPrfx('my-prefix-')])
  .process(css)
  .then(function(result) {
    console.log(result);
  });
```

Would you be able to update the example or, alternatively, I can create a PR when I get a chance...

**Comment by thompsongl** [comment]
Finally getting around to marking this repo as no longer maintained. At this point I'm guessing even this snippet is out of date.
Thanks for the offer, and my apologies for poor communication. If you still want to open an updated PR, I'd probably be open to it.
