### ISSUE TITLE
README : unmaintained repo (?)

### ISSUE THREAD

**Issue by GabrielDelepine** [thompsongl/postcss-class-prefix#16]
Hi @thompsongl 

First, I'd like to thank you for this repository.

In [this comment](https://github.com/thompsongl/postcss-class-prefix/issues/13#issuecomment-241462901), you explained this repo is not really maintained anymore. I totally understand, it's common. However I would recommend you to explain that in your README file and mention another repository such as [postcss-prefixer](https://github.com/marceloucker/postcss-prefixer) for exemple.

**Comment by thompsongl** [comment]
Finally getting to this. Done in efe23b170b3cbbd5ec0eee57d45497a4e00e009d
