### ISSUE TITLE
ignore option doesn't work with an array

### ISSUE THREAD

**Issue by simonsmith** [thompsongl/postcss-class-prefix#2]
The documentation shows that you can pass an array of regexs or strings to match against, but in practice it doesn't loop over such an array.

I think it would be great if it did, as right now I have to match multiple things in one regex.

Thoughts?

Also, it references `rework` in the code samples, instead of `postcss`

**Comment by thompsongl** [comment]
A loop through the array is the definitely the intended behavior; I just didn't have tests for or projects using it.
Thanks for catching that.

Ah, residual rework. I'll update the readme quick.
