### ISSUE TITLE
Make it a selector prefixer too

### ISSUE THREAD

**Issue by hbrls** [thompsongl/postcss-class-prefix#9]
I've changed it in [my fork](https://github.com/hbrls/postcss-selector-prefix/commit/b39667f0ce8fa55672106dd4eb52a8086f264b1f). Maybe some more options is enough.

``` css
.a .b { ... }
```

class prefix

``` css
.pre-a .pre-b { ... }
```

selector prefix

``` css
.pre .a .b { ... }
```

**Comment by valentin-radulescu-hs** [comment]
@hbrls There's a separate postcss plugin that can do this [postcss-prefix-selector](https://github.com/jonathanong/postcss-prefix-selector)

**Comment by hbrls** [comment]
exactly, thank you!
